name: Release Please

on:
  push:
    branches:
      - main

permissions: {}

jobs:
  release-please:
    name: Open or update release PR
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: google-github-actions/release-please-action@v4
        with:
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json
